server:
  port: 3000
  servlet:
    session:
      cookie:
        same-site: "lax"

spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: azure
            scope:
              - openid
              - profile
              - email
        provider:
          azure:
            issuer-uri: "https://login.microsoftonline.com//v2.0"

app:
  security:
    enabled: true
    allowed-domain: "astro.com.my"
    jwt:
      secret: "your-super-secret-key-that-is-at-least-256-bits-long"
      expiration-ms: 3600000

aws:
  accessKey:
  secretKey:
  sessionToken:
  region: "ap-southeast-1"
  role:
  mfa_arn:
  profile:


logging:
  level:
    org.springframework.security: DEBUG
