server:
  port: 3000

spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: azure
            scope:
              - openid
              - profile
              - email
        provider:
          azure:
            issuer-uri: "https://login.microsoftonline.com/<<tenant_id>>/v2.0"
            user-info-uri: "https://graph.microsoft.com/oidc/userinfo"
            user-name-attribute: "sub"
  datasource:
    url: jdbc:mysql://localhost:3306/ues-portal
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

app:
  client:
    domain: "http://localhost:5000"
  security:
    enabled: true
    allowed-domain: "astro.com.my"
    jwt:
      secret: "z$C&F)J@NcRfUjXn2r5u8x/A?D(G-KaPdSgVkYp3s6v9y$B&E)H@MbQeThWmZq4t"
      expiration-ms: 3600000

aws:
  accessKey:
  secretKey:
  sessionToken:
  region: "ap-southeast-1"
  role:
  mfa_arn:
  profile:


logging:
  level:
    org.springframework.security: DEBUG
